version: "3.8"

services:
  411_db:
    container_name: 411_postgres
    image: postgres:13.0-alpine
    volumes:
      - 411_postgres_data:/var/lib/postgresql/data
      - ./import:/mnt/import
    env_file:
      - ./.env.prod
    networks:
      - "backend"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432

  411_api:
    container_name: 411_django
    image: registry.gitlab.com/rysie/reddit-411-nsfw:prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn brain.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    volumes:
      - .:/usr/src/app/
    networks:
      - "backend"
    ports:
      - 8000:8000
    depends_on:
      - 411_db
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      # DB
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      # PRAW
      PRAW_CLIENT_ID: ${PRAW_CLIENT_ID}
      PRAW_CLIENT_SECRET: ${PRAW_CLIENT_SECRET}
      PRAW_PASSWORD: ${PRAW_PASSWORD}
      PRAW_USERNAME: ${PRAW_USERNAME}
      PRAW_USER_AGENT: ${PRAW_USER_AGENT}

networks:
  backend:
    driver: "bridge"

volumes:
  411_postgres_data: